"""Distill the cached shareholder letters into the Buffett Researcher's principles doc.

This is the "training" step for the Buffett Researcher. There is no
fine-tuning: a map-reduce pass over the letters produces a compact,
reusable statement of how Buffett evaluates a business, and that document
is injected into the agent's prompt at runtime.

- Map: one cheap call per letter extracts the durable evaluative principles
  it contains, ignoring that year's operating results. Notes are cached to
  ``{data_cache_dir}/buffett_letters/_notes/{year}.md`` so re-runs are free.
- Reduce: the notes are folded (in batches, if the corpus is large) into a
  single principles document written to the override path that
  ``load_buffett_principles`` prefers over the shipped baseline.

Only the synthesized document is retained for prompting; the copyrighted
letter text stays in the local cache and is never redistributed.

Usage:
    uv run python scripts/fetch_buffett_letters.py
    uv run python scripts/distill_buffett_principles.py
    uv run python scripts/distill_buffett_principles.py --provider anthropic --limit 5
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tradingagents.agents.researchers.buffett_researcher import principles_override_path
from tradingagents.dataflows.config import get_config
from tradingagents.llm_clients import create_llm_client

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch_buffett_letters import corpus_dir, load_corpus  # noqa: E402

# Letters run to ~90k characters. Trim the map input rather than risk a
# context error on a small model; the philosophy is spread throughout, so a
# truncated letter still yields usable notes.
MAX_LETTER_CHARS = 60_000

# Fold notes in batches so the reduce step stays inside a modest context
# window regardless of how many letters were fetched.
REDUCE_BATCH_CHARS = 120_000

MAP_PROMPT = """Below is Warren Buffett's Berkshire Hathaway shareholder letter for {year}.

Extract only the DURABLE, TRANSFERABLE principles it contains about how to evaluate
a business as an investment. Ignore that year's operating results, segment figures,
personnel notes, and anything specific to Berkshire's own subsidiaries except where
Buffett uses them to illustrate a general rule.

Organize what you find under whichever of these headings apply:
- Circle of competence
- Economic moat / franchise vs. commodity business
- Owner earnings and intrinsic value
- Margin of safety and price discipline
- Management quality, candor, and capital allocation
- Return on unleveraged equity and the cost of growth
- Accounting red flags
- Market psychology and temperament
- The "too hard" pile

Be concrete. Where Buffett states a rule in a memorable way, quote the phrase in
under 15 words. Keep the whole response under 400 words. If the letter contains
little durable philosophy, say so briefly instead of padding.

LETTER:
{letter}"""

REDUCE_PROMPT = """You are assembling a decision checklist that lets an analyst evaluate any company
the way Warren Buffett would.

Below are notes extracted from {count} Berkshire Hathaway shareholder letters
({span}). Synthesize them into ONE coherent markdown document. Merge duplicates,
resolve overlaps, and keep the strongest formulation of each idea. Where Buffett's
thinking visibly evolved (for example, from cigar-butt bargains to paying a fair
price for a wonderful business), say so explicitly rather than averaging it away.

Structure the output with these top-level sections:

## Circle of Competence
## Economic Moats and Franchise Quality
## Owner Earnings and Intrinsic Value
## Margin of Safety and Price Discipline
## Management: Candor and Capital Allocation
## Return on Unleveraged Equity
## Accounting Red Flags
## Temperament and Mr. Market
## The Too-Hard Pile

End with:

## Evaluation Checklist

a numbered list of the concrete questions to ask about a specific company, in the
order Buffett would ask them.

Write it as operational guidance an analyst can apply, not as a biography. Keep
short verbatim phrases where they sharpen a point. Target 1,200-1,800 words. Output
only the markdown document, with no preamble.

NOTES:
{notes}"""

FOLD_PROMPT = """Below are notes extracted from several Berkshire Hathaway shareholder letters.
Consolidate them into a single set of notes covering the same ground with the
duplicates merged and the strongest formulation of each idea kept. Preserve
concrete rules and short verbatim phrases. Do not add commentary.

NOTES:
{notes}"""

HEADER = """<!--
Generated by scripts/distill_buffett_principles.py from the Berkshire Hathaway
shareholder letters ({span}). This file is a synthesis, not letter text.
Delete it to fall back to the baseline document shipped with the package.
-->

# How Warren Buffett Evaluates a Business

"""


def notes_dir() -> Path:
    path = corpus_dir() / "_notes"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _invoke(llm, prompt: str) -> str:
    return llm.invoke(prompt).content.strip()


def map_letters(llm, letters: dict[int, str], force: bool) -> dict[int, str]:
    """Extract per-letter principle notes, caching each to disk."""
    notes: dict[int, str] = {}
    for index, (year, letter) in enumerate(sorted(letters.items()), start=1):
        path = notes_dir() / f"{year}.md"
        if path.exists() and path.stat().st_size > 0 and not force:
            notes[year] = path.read_text(encoding="utf-8")
            print(f"  [{index}/{len(letters)}] {year}: cached")
            continue

        print(f"  [{index}/{len(letters)}] {year}: extracting...", flush=True)
        note = _invoke(llm, MAP_PROMPT.format(year=year, letter=letter[:MAX_LETTER_CHARS]))
        path.write_text(note, encoding="utf-8")
        notes[year] = note
    return notes


def _batch(notes: dict[int, str]) -> list[str]:
    """Group year-labelled notes into chunks under the reduce context budget."""
    batches: list[str] = []
    current: list[str] = []
    size = 0
    for year, note in sorted(notes.items()):
        block = f"### From the {year} letter\n{note}\n"
        if current and size + len(block) > REDUCE_BATCH_CHARS:
            batches.append("\n".join(current))
            current, size = [], 0
        current.append(block)
        size += len(block)
    if current:
        batches.append("\n".join(current))
    return batches


def reduce_notes(llm, notes: dict[int, str]) -> str:
    """Fold per-letter notes into the final principles document."""
    batches = _batch(notes)
    while len(batches) > 1:
        print(f"  folding {len(batches)} batches...", flush=True)
        folded = [_invoke(llm, FOLD_PROMPT.format(notes=batch)) for batch in batches]
        batches = _batch(dict(enumerate(folded)))

    years = sorted(notes)
    span = f"{years[0]}-{years[-1]}" if years else "no letters"
    print("  synthesizing final document...", flush=True)
    return _invoke(
        llm,
        REDUCE_PROMPT.format(count=len(notes), span=span, notes=batches[0]),
    )


def main() -> int:
    config = get_config()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--provider", default=config["llm_provider"])
    parser.add_argument("--map-model", default=config["quick_think_llm"])
    parser.add_argument("--reduce-model", default=config["deep_think_llm"])
    parser.add_argument("--limit", type=int, help="Only process the N most recent letters")
    parser.add_argument("--force", action="store_true", help="Re-extract cached notes")
    parser.add_argument("--out", type=Path, help="Override the output path")
    args = parser.parse_args()

    letters = load_corpus()
    if not letters:
        print(f"No letters found in {corpus_dir()}.")
        print("Run scripts/fetch_buffett_letters.py first.")
        return 1
    if args.limit:
        letters = dict(sorted(letters.items())[-args.limit :])

    years = sorted(letters)
    span = f"{years[0]}-{years[-1]}"
    print(f"Corpus: {len(letters)} letters ({span})")
    print(f"Provider: {args.provider} | map: {args.map_model} | reduce: {args.reduce_model}\n")

    map_llm = create_llm_client(provider=args.provider, model=args.map_model).get_llm()
    reduce_llm = create_llm_client(provider=args.provider, model=args.reduce_model).get_llm()

    print("Map phase:")
    notes = map_letters(map_llm, letters, force=args.force)
    print("\nReduce phase:")
    document = reduce_notes(reduce_llm, notes)

    destination = args.out or principles_override_path()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(HEADER.format(span=span) + document.strip() + "\n", encoding="utf-8")

    print(f"\nWrote {len(document):,} chars to {destination}")
    print("The Buffett Researcher will prefer this over the shipped baseline.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
